### ISSUE TITLE
feat: MainView 구조 작성 및 구현

### ISSUE THREAD

**Issue by bulmang** [ToucherTeam/Toucher#1]
## ✏️ Summary

MainView 구조와 View 작업을 완성합니다.
<br>

## ✨ Description

MainView를 관리해주는
MainViewModel을 구현합니다.

### 🗂 Folder Structure

```
Toucher
  |
  └── Aenitto
          |── 🗂 View
          │   │── 📁 Main
          │   │   │ ── 📑 MainView
          │   │   │ ── 📑 MainViewModel
```
<br>

## ✓ Todo
- [ ] MainView UI 구현
- [ ] MainViewModel 구현 및 연결
- [ ] 다른 View들 연결

<br>
