### ISSUE TITLE
feat: LongTap 뷰 구현

### ISSUE THREAD

**Issue by hyunjuntyler** [ToucherTeam/Toucher#2]
## ✏️ Summary

Long Tap 관련 기능, 뷰를 구현합니다.

<br>

## ✨ Description

<br>

## ✓ Todo
- [ ] 기본 롱탭 예제
- [ ] 카메라 클릭 예제
- [ ] 사진첩 확대 기능 구현
- [ ] 롱탭 시 원이 커지는 애니메이션 구현

<br>
