### ISSUE TITLE
feat: Swipe,Pan Gesture UI, Component 변경 및 기능 추가

### ISSUE THREAD

**Issue by bulmang** [ToucherTeam/Toucher#57]
## ✏️ Summary

스와이프 뷰에서 변경된 디자인을 적용하고  실패 조건을 추가하여 실패 하였을 때 화면은 구현합니다.
<br>

## ✨ Description

`SwipeExampleView1`에서 Rectangle의 색을 변경합니다. 추가로 실패 조건과 실패 하였을때 배경색, 글씨색을 변경합니다.
`SwipeExampleView2`에서도 실패 조건과 실패 하였을 때 배경색, 글씨색을  변경합니다.
뷰 이동도 성공하였을 때 2.5초 후에 자동으로 이동이 되도록 변경합니다.
<br>

## ✓ Todo
- [x] Rectangle UI 변경
- [x] 실패 조건 추가
- [x] 실패 하였을 때 배경색, 글씨색 변경
- [x] 성공 후 네비게이션 자동 이동

<br>
