### ISSUE TITLE
fix: QA 적용

### ISSUE THREAD

**Issue by hyunjuntyler** [ToucherTeam/Toucher#60]
## ✏️ Summary
- 내부 QA 적용

<br>

## ✨ Description
- 내부 QA 후 수정이 필요한 부분 적용

<br>

## ✓ Todo
- [x] 카메라 부분 인터렉션
- [x] 확대뷰 디테일 적용
- [x] 회전하기 문구 변경
- [x] 박스 정렬 (왼쪽 패딩 40)
- [x] 메인화면 상단 박스 추가
- [x] 더블탭, 핀치 이미지 변경
- [x] 롱프레스 이미지 변경
- [x] 학습내용 저장
