### ISSUE TITLE
feat: 오프라인시 데이터 저장

### ISSUE THREAD

**Issue by bulmang** [ToucherTeam/Toucher#86]
## ✏️ Summary

인터넷 연결이 없을 상황을 대비하여 데이터 저장을 오프라인으로 하는 방법을 개발합니다.
<br>

## ✨ Description

현재 상황 : 
- 타일러께서 만들어 주신 데이터 저장을 이용하여 오프라인 데이터를 저장합니다.
- 온라인으로 전환시 오프라인 데이터들을 서버로 보내게 합니다.
<br>

## ✓ Todo
- [x] 데이터 모델 생성
- [x] 인터넷 연결시 자동 데이터 전송 기능 리서치 및 테스트
- [x] 모든 데이터 연결 작업

<br>
